schema_version: 1

context:
  name: iregi
  version: 1.1.0

recipe:
  name: ${{ name }}-suite
  version: ${{ version }}

source:
  - url: https://github.com/hep-packaging-coordination/mg5amcnlo-release-mirror/releases/download/3.5.7/MG5_aMC_v3.5.7.tar.gz
    sha256: ca3e027f078438318bd4143a102aebc2d51358f537b5d52bbc574fe49a6a901e
    patches:
      # FIXME: makefile_ML5_lib tries to build everything by default
      - makefile_ML5_lib.patch
      # FIXME: mg5amcnlo uses 'avh_olo_forIREGI' instead of 'avh_olo' is mis_warp.f90
      - use-avh_olo.patch

build:
  number: 3

outputs:
  - package:
      name: ${{ name }}-static
    build:
      skip: win
      script:
        - cd vendor/IREGI/src/
        # Remove vendored code that is on conda-forge
        - rm -rf oneloop
        - rm -rf qcdloop
        - rm makefile
        - rm makefile_oneloop
        - rm makefile_qcdloop
        # Build
        # Enable extended-source with '-ffixed-line-length-none' for long lines
        # c.f. https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html#index-ffixed-line-length-n
        # The build is not parallel safe, so must compile single threaded
        - make -f makefile_ML5_lib FC=$FC FFLAGS="$FFLAGS -std=legacy -Wall -ffixed-line-length-none -I$PREFIX/include/oneloop"
        # Install
        - mv libiregi.a $PREFIX/lib/
        - mkdir -p $PREFIX/include/iregi
        - mv *.mod $PREFIX/include/iregi/
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('fortran') }}
        - make
        - libtool
        - if: build_platform != target_platform
          then: oneloop-static
      host:
        - oneloop-static
    tests:
      - package_contents:
          strict: true
          files:
            - lib/libiregi.a
          include:
            - iregi/binary_tree.mod
            - iregi/cmatrix_base.mod
            - iregi/cpave_reduce.mod
            - iregi/csi_reduce.mod
            - iregi/cti_reduce.mod
            - iregi/funlib.mod
            - iregi/global.mod
            - iregi/gti_reduce.mod
            - iregi/kinematics.mod
            - iregi/linear_algebra.mod
            - iregi/matrices.mod
            - iregi/matrix_base.mod
            - iregi/mis_warp.mod
            - iregi/pave_reduce.mod
            - iregi/si_reduce.mod
            - iregi/special_fun.mod
            - iregi/ti_reduce.mod

about:
  summary: "IREGI: one-loop tensor Integral REduction with General propagator Indices"
  description: |
    IREGI is a package for one-loop tensor Integral REduction with General
    propagator Indices.

    The algorithm was proposed by G. Duplancic, B. Nizic
    (DOI: [10.1140/epjc/s2004-01723-7](https://doi.org/10.1140/epjc/s2004-01723-7)).

    This implementation for MADLOOP5 in MadGraph5_aMC@NLO was originally
    authored by Hua-Sheng Shao.
  # IREGI source only exists in the MG5_aMC@NLO repo and so has the same license
  # modified University of Illinois/NCSA license
  license: LicenseRef-NCSA
  license_file: LICENSE
  homepage: https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x/vendor/IREGI/src
  repository: https://github.com/mg5amcnlo/mg5amcnlo/tree/3.x/vendor/IREGI/src

extra:
  feedstock-name: iregi
  recipe-maintainers:
    - matthewfeickert
